import XCTest
@testable import Tally

// Visible suite. Run: swift test
// Do not edit this file -- fix Sources/Tally/Tally.swift.
final class TallyTests: XCTestCase {
    func testTotalSmall() async {
        let r = await total(workers: 8, perWorker: 1000)
        XCTAssertEqual(r, 8000)
    }
}
