import XCTest
@testable import RomanKit

// Visible test suite. Run: swift test
// Do not edit this file to make it pass -- fix Sources/RomanKit/RomanKit.swift.
final class RomanKitTests: XCTestCase {
    func testToRomanBasic() throws {
        XCTAssertEqual(try toRoman(1), "I")
        XCTAssertEqual(try toRoman(3), "III")
    }

    func testToRomanSubtractive() throws {
        XCTAssertEqual(try toRoman(4), "IV")
        XCTAssertEqual(try toRoman(9), "IX")
    }

    func testFromRomanBasic() throws {
        XCTAssertEqual(try fromRoman("III"), 3)
    }

    func testFromRomanSubtractive() throws {
        XCTAssertEqual(try fromRoman("IV"), 4)
        XCTAssertEqual(try fromRoman("IX"), 9)
    }
}
