"""Visible test suite for calc.evaluate. Run: python3 test_calc.py

Do not edit this file to make it pass -- fix calc.py instead.
"""

from calc import evaluate

CASES = [
    ("1+1", 2),
    ("2+3*4", 14),
    ("(2+3)*4", 20),
    ("10-2-3", 5),
    ("1+2*3", 7),
    ("2*3+4", 10),
    ("7/2", 3),
]


def main() -> None:
    failures = []
    for expr, want in CASES:
        try:
            got = evaluate(expr)
        except Exception as e:  # noqa: BLE001
            failures.append((expr, want, f"ERROR: {type(e).__name__}: {e}"))
            continue
        if got != want:
            failures.append((expr, want, got))

    for expr, want, got in failures:
        print(f"FAIL {expr!r}: want {want}, got {got}")
    print(f"{len(CASES) - len(failures)}/{len(CASES)} passed")
    raise SystemExit(1 if failures else 0)


if __name__ == "__main__":
    main()
